Persistent configuration as config.toml
kentik/sla_dashboard_webapp pull request #5
Opened 2021-05-10 09:48 UTC by mateuszmidor

KNTK-221

2021-05-10 10:26 UTC, lukaa12 approved these changes

2021-05-10 14:33 UTC, Fenthick requested changes

2021-05-10 14:33 UTC, Fenthick commented on config.ini
> +
I think that we should use TOML, because it is better, according to https://www.python.org/dev/peps/pep-0518/#overview-of-file-formats-considered

2021-05-10 14:33 UTC, Fenthick commented on config.ini
> +# test id to display the data matrix for
```suggestion
# test ID to display the data matrix for
```

2021-05-10 14:33 UTC, Fenthick commented on presentation/main_view.py
> +    matrix = make_mesh_test_matrix_layout(mesh, config)
```suggestion
```
This is unused so it can be removed

2021-05-10 14:33 UTC, Fenthick commented on presentation/main_view.py
> +                + " where lower latency limit was set to 300ms and higher limit was set to 400ms."
300 ms is no longer true. Maybe use values for config here.

2021-05-11 11:50 UTC, Fenthick commented on config.ini
> +[DEFAULT]
Done

2021-05-11 11:50 UTC, Fenthick commented on config.ini
> +
Done

2021-05-11 11:50 UTC, Fenthick commented on presentation/main_view.py
> +    matrix = make_mesh_test_matrix_layout(mesh, config)
Done

2021-05-11 11:50 UTC, Fenthick approved these changes

2021-05-11 18:05 UTC, mmac-m3a approved these changes
It is good to go in,  but address my comments in the next pull request.

2021-05-11 18:13 UTC, merged

2021-05-12 05:07 UTC, mateuszmidor commented on config.ini
> +# if above, then display connection as deteriorated
I will update the config according to your comments once I'm done with data caching that I'm working on already.