Render connection matrix using dash table
kentik/sla_dashboard_webapp pull request #63
Opened 2021-09-10 10:55 UTC by mateuszmidor

KNTK-294
    display measurement data with coloring
    detailed data in hover text
    navigate to timeseries view when clicked on specific cell
    support 60 x 60 matrix

2021-09-10 18:25 UTC, mmac-m3a requested changes
It is mostly good! We though need to either make agent labels configurable or use `agent.name` (see my more detailed comment). Agent aliases are duplicated. For example agents 1022 and 662, both have alias "Frankfurt, Germany". With my fix taking names from the `mesh` section of augmented health results, the first one should have `name` "ibm, eu-de" and the latter "Frankfurt am Main, Choopa,US" (which is confusing, but we cannot fix that).
I've only now noticed that the "agent name fix" does not work in the current version at HEAD in master. For example, agent 1022 has label "eu-de" in the matrix (should be "ibm, eu-de"). I've checked the health data returned for my mesh test by the API, and it is all there.  Looks like your refactor adding `MeshConfig` somehow broke it. I'm not sure how, but it did work before.

2021-09-13 07:53 UTC, mateuszmidor commented on presentation/matrix_view.py
> +            tooltip_lines.append(f"Time stamp: {health.timestamp.strftime('%x %X %Z')}")
Updating.

2021-09-13 07:59 UTC, mateuszmidor commented on presentation/matrix_view.py
> +        return "\n".join(tooltip_lines)
Updating

2021-09-13 08:05 UTC, mateuszmidor commented on presentation/matrix_view.py
> +    def _tag_to_color(self, tag: CellTag) -> MatrixCellColor:
Updating

2021-09-13 08:07 UTC, mateuszmidor commented on presentation/matrix_view.py
> +    if val < warning_threshold:
Updating

2021-09-13 08:19 UTC, mateuszmidor commented on presentation/matrix_view.py
> -    return agent.name
Adding configurable agent label formatting string

2021-09-13 16:56 UTC, mmac-m3a approved these changes
We still need to fix agent names (we are not getting the right ones at the moment), but it can be done separately.

2021-09-13 16:57 UTC, merged